<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Convivium.Application\Convivium.Application.csproj" />
  </ItemGroup>

</Project>
