// <auto-generated />
using System;
using Convivium.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Convivium.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConviviumDbContext))]
    [Migration("20260915203516_MedicaoIndividual")]
    partial class MedicaoIndividual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Convivium.Domain.Billing.BillingCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ApportionableTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("apportionable_total");

                    b.Property<decimal>("ChargedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("charged_total");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_person_id");

                    b.Property<int>("Competence")
                        .HasColumnType("integer")
                        .HasColumnName("competence");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<decimal>("ReserveFundRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("reserve_fund_rate");

                    b.Property<decimal>("ReserveFundTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("reserve_fund_total");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_billing_cycles");

                    b.HasIndex("CondominiumId", "Competence")
                        .IsUnique()
                        .HasDatabaseName("ix_billing_cycles_condominium_id_competence");

                    b.ToTable("billing_cycles", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Billing.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BarcodeLine")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("barcode_line");

                    b.Property<Guid?>("BillingCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_cycle_id");

                    b.Property<int>("Competence")
                        .HasColumnType("integer")
                        .HasColumnName("competence");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("ExternalSlipId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_slip_id");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notified_at");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("paid_on");

                    b.Property<Guid?>("PayerPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_person_id");

                    b.Property<string>("PixPayload")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("pix_payload");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("public_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_charges");

                    b.HasIndex("PayerPersonId")
                        .HasDatabaseName("ix_charges_payer_person_id");

                    b.HasIndex("PublicToken")
                        .IsUnique()
                        .HasDatabaseName("ix_charges_public_token");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_charges_unit_id");

                    b.HasIndex("BillingCycleId", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_charges_billing_cycle_id_unit_id")
                        .HasFilter("billing_cycle_id IS NOT NULL");

                    b.HasIndex("CondominiumId", "Status", "DueDate")
                        .HasDatabaseName("ix_charges_condominium_id_status_due_date");

                    b.HasIndex("CondominiumId", "UnitId", "Competence")
                        .HasDatabaseName("ix_charges_condominium_id_unit_id_competence");

                    b.ToTable("charges", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Billing.ChargeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_charge_items");

                    b.HasIndex("ChargeId")
                        .HasDatabaseName("ix_charge_items_charge_id");

                    b.HasIndex("LedgerAccountId")
                        .HasDatabaseName("ix_charge_items_ledger_account_id");

                    b.ToTable("charge_items", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Billing.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_id");

                    b.Property<Guid?>("LedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_entry_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("paid_on");

                    b.Property<Guid?>("RegisteredByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by_person_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("ChargeId")
                        .HasDatabaseName("ix_payments_charge_id");

                    b.HasIndex("CondominiumId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_condominium_id_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.HasIndex("CondominiumId", "PaidOn")
                        .HasDatabaseName("ix_payments_condominium_id_paid_on");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Condominiums.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.HasIndex("CondominiumId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_blocks_condominium_id_name");

                    b.ToTable("blocks", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Condominiums.Condominium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("PixKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pix_key");

                    b.Property<string>("PixKeyType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("pix_key_type");

                    b.Property<string>("PixReceiverCity")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("pix_receiver_city");

                    b.Property<string>("PixReceiverName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("pix_receiver_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_condominiums");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_condominiums_cnpj")
                        .HasFilter("cnpj IS NOT NULL");

                    b.ToTable("condominiums", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Condominiums.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AreaM2")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("area_m2");

                    b.Property<Guid?>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<decimal>("IdealFraction")
                        .HasPrecision(12, 8)
                        .HasColumnType("numeric(12,8)")
                        .HasColumnName("ideal_fraction");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("BlockId")
                        .HasDatabaseName("ix_units_block_id");

                    b.HasIndex("CondominiumId", "BlockId", "Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_units_condominium_id_block_id_identifier");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Expenses.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("Competence")
                        .HasColumnType("integer")
                        .HasColumnName("competence");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_person_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("document_number");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsApportionable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_apportionable");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<Guid?>("LedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_entry_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("paid_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UtilityBillId")
                        .HasColumnType("uuid")
                        .HasColumnName("utility_bill_id");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("LedgerAccountId")
                        .HasDatabaseName("ix_expenses_ledger_account_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_expenses_supplier_id");

                    b.HasIndex("UtilityBillId")
                        .HasDatabaseName("ix_expenses_utility_bill_id")
                        .HasFilter("utility_bill_id IS NOT NULL");

                    b.HasIndex("CondominiumId", "Competence", "Status")
                        .HasDatabaseName("ix_expenses_condominium_id_competence_status");

                    b.HasIndex("CondominiumId", "DueDate", "Status")
                        .HasDatabaseName("ix_expenses_condominium_id_due_date_status");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Expenses.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Document")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("CondominiumId", "Document")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_condominium_id_document")
                        .HasFilter("document IS NOT NULL");

                    b.HasIndex("CondominiumId", "Name")
                        .HasDatabaseName("ix_suppliers_condominium_id_name");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Finance.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("account_number");

                    b.Property<string>("Agency")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("agency");

                    b.Property<string>("BankCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("bank_code");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsReserveFund")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reserve_fund");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("opening_balance");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("date")
                        .HasColumnName("opening_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bank_accounts");

                    b.HasIndex("CondominiumId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_accounts_condominium_id_name");

                    b.ToTable("bank_accounts", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Finance.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsApportionable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_apportionable");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nature");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ledger_accounts");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_ledger_accounts_parent_id");

                    b.HasIndex("CondominiumId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_accounts_condominium_id_code");

                    b.ToTable("ledger_accounts", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Finance.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<int>("Competence")
                        .HasColumnType("integer")
                        .HasColumnName("competence");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_person_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("direction");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("document_number");

                    b.Property<Guid?>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<DateTimeOffset?>("ReconciledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reconciled_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("ix_ledger_entries_bank_account_id");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("ix_ledger_entries_expense_id")
                        .HasFilter("expense_id IS NOT NULL");

                    b.HasIndex("LedgerAccountId")
                        .HasDatabaseName("ix_ledger_entries_ledger_account_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_ledger_entries_payment_id")
                        .HasFilter("payment_id IS NOT NULL");

                    b.HasIndex("CondominiumId", "BankAccountId", "Date")
                        .HasDatabaseName("ix_ledger_entries_condominium_id_bank_account_id_date");

                    b.HasIndex("CondominiumId", "Competence", "LedgerAccountId")
                        .HasDatabaseName("ix_ledger_entries_condominium_id_competence_ledger_account_id");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Metering.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Competence")
                        .HasColumnType("integer")
                        .HasColumnName("competence");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentReading")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("current_reading");

                    b.Property<decimal>("PreviousReading")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("previous_reading");

                    b.Property<DateOnly>("ReadOn")
                        .HasColumnType("date")
                        .HasColumnName("read_on");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Utility")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("utility");

                    b.HasKey("Id")
                        .HasName("pk_meter_readings");

                    b.HasIndex("UnitId", "Utility", "Competence")
                        .HasDatabaseName("ix_meter_readings_unit_id_utility_competence");

                    b.HasIndex("CondominiumId", "Utility", "Competence", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_meter_readings_condominium_id_utility_competence_unit_id");

                    b.ToTable("meter_readings", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Notifications.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AttachChargePdf")
                        .HasColumnType("boolean")
                        .HasColumnName("attach_charge_pdf");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid?>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<Guid?>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<string>("TextBody")
                        .HasColumnType("text")
                        .HasColumnName("text_body");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("to_address");

                    b.Property<string>("ToName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("to_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_email_messages");

                    b.HasIndex("ChargeId")
                        .HasDatabaseName("ix_email_messages_charge_id")
                        .HasFilter("charge_id IS NOT NULL");

                    b.HasIndex("CondominiumId")
                        .HasDatabaseName("ix_email_messages_condominium_id");

                    b.HasIndex("Status", "ScheduledFor")
                        .HasDatabaseName("ix_email_messages_status_scheduled_for");

                    b.ToTable("email_messages", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.People.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_memberships");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_memberships_person_id");

                    b.HasIndex("CondominiumId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_memberships_condominium_id_person_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("InviteTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invite_token_expires_at");

                    b.Property<string>("InviteTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invite_token_hash");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_admin");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_people_cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_people_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("InviteTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_people_invite_token_hash")
                        .HasFilter("invite_token_hash IS NOT NULL");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.People.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("PersonId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_person_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.People.UnitOccupancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<bool>("IsBillingResponsible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_billing_responsible");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("relation");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_unit_occupancies");

                    b.HasIndex("CondominiumId")
                        .HasDatabaseName("ix_unit_occupancies_condominium_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_unit_occupancies_person_id");

                    b.HasIndex("UnitId", "PersonId", "Relation")
                        .HasDatabaseName("ix_unit_occupancies_unit_id_person_id_relation");

                    b.ToTable("unit_occupancies", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Utilities.UtilityBill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BarcodeLine")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("barcode_line");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominium_id");

                    b.Property<decimal?>("ConsumptionCubicMeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("consumption_cubic_meters");

                    b.Property<decimal?>("ConsumptionKwh")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("consumption_kwh");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<Guid?>("ImportedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("imported_by_person_id");

                    b.Property<string>("InstallationCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("installation_code");

                    b.Property<string>("ParseWarnings")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("parse_warnings");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<int?>("ReferenceMonth")
                        .HasColumnType("integer")
                        .HasColumnName("reference_month");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("source_file_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_utility_bills");

                    b.HasIndex("CondominiumId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_utility_bills_condominium_id_content_hash");

                    b.HasIndex("CondominiumId", "Provider", "Status")
                        .HasDatabaseName("ix_utility_bills_condominium_id_provider_status");

                    b.ToTable("utility_bills", (string)null);
                });

            modelBuilder.Entity("Convivium.Domain.Billing.Charge", b =>
                {
                    b.HasOne("Convivium.Domain.Billing.BillingCycle", "BillingCycle")
                        .WithMany("Charges")
                        .HasForeignKey("BillingCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_charges_billing_cycles_billing_cycle_id");

                    b.HasOne("Convivium.Domain.People.Person", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerPersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_charges_people_payer_person_id");

                    b.HasOne("Convivium.Domain.Condominiums.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charges_units_unit_id");

                    b.Navigation("BillingCycle");

                    b.Navigation("Payer");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Convivium.Domain.Billing.ChargeItem", b =>
                {
                    b.HasOne("Convivium.Domain.Billing.Charge", "Charge")
                        .WithMany("Items")
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_charge_items_charges_charge_id");

                    b.HasOne("Convivium.Domain.Finance.LedgerAccount", "LedgerAccount")
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_charge_items_ledger_accounts_ledger_account_id");

                    b.Navigation("Charge");

                    b.Navigation("LedgerAccount");
                });

            modelBuilder.Entity("Convivium.Domain.Billing.Payment", b =>
                {
                    b.HasOne("Convivium.Domain.Billing.Charge", "Charge")
                        .WithMany("Payments")
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_charges_charge_id");

                    b.Navigation("Charge");
                });

            modelBuilder.Entity("Convivium.Domain.Condominiums.Block", b =>
                {
                    b.HasOne("Convivium.Domain.Condominiums.Condominium", "Condominium")
                        .WithMany("Blocks")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_condominiums_condominium_id");

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("Convivium.Domain.Condominiums.Condominium", b =>
                {
                    b.OwnsOne("Convivium.Domain.Condominiums.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CondominiumId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("address_district");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("CondominiumId");

                            b1.ToTable("condominiums");

                            b1.WithOwner()
                                .HasForeignKey("CondominiumId")
                                .HasConstraintName("fk_condominiums_condominiums_id");
                        });

                    b.OwnsOne("Convivium.Domain.Condominiums.BillingSettings", "Billing", b1 =>
                        {
                            b1.Property<Guid>("CondominiumId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("DefaultApportionmentMethod")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("billing_default_apportionment_method");

                            b1.Property<int>("DueDay")
                                .HasColumnType("integer")
                                .HasColumnName("billing_due_day");

                            b1.Property<decimal>("LateFeeRate")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("billing_late_fee_rate");

                            b1.Property<decimal>("MonthlyInterestRate")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("billing_monthly_interest_rate");

                            b1.Property<decimal>("ReserveFundRate")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("billing_reserve_fund_rate");

                            b1.HasKey("CondominiumId");

                            b1.ToTable("condominiums");

                            b1.WithOwner()
                                .HasForeignKey("CondominiumId")
                                .HasConstraintName("fk_condominiums_condominiums_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Billing")
                        .IsRequired();
                });

            modelBuilder.Entity("Convivium.Domain.Condominiums.Unit", b =>
                {
                    b.HasOne("Convivium.Domain.Condominiums.Block", "Block")
                        .WithMany("Units")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_units_blocks_block_id");

                    b.HasOne("Convivium.Domain.Condominiums.Condominium", "Condominium")
                        .WithMany("Units")
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_units_condominiums_condominium_id");

                    b.Navigation("Block");

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("Convivium.Domain.Expenses.Expense", b =>
                {
                    b.HasOne("Convivium.Domain.Finance.LedgerAccount", "LedgerAccount")
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_ledger_accounts_ledger_account_id");

                    b.HasOne("Convivium.Domain.Expenses.Supplier", "Supplier")
                        .WithMany("Expenses")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_suppliers_supplier_id");

                    b.Navigation("LedgerAccount");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Convivium.Domain.Finance.BankAccount", b =>
                {
                    b.HasOne("Convivium.Domain.Condominiums.Condominium", "Condominium")
                        .WithMany()
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bank_accounts_condominiums_condominium_id");

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("Convivium.Domain.Finance.LedgerAccount", b =>
                {
                    b.HasOne("Convivium.Domain.Finance.LedgerAccount", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ledger_accounts_ledger_accounts_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Convivium.Domain.Finance.LedgerEntry", b =>
                {
                    b.HasOne("Convivium.Domain.Finance.BankAccount", "BankAccount")
                        .WithMany("Entries")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_bank_accounts_bank_account_id");

                    b.HasOne("Convivium.Domain.Finance.LedgerAccount", "LedgerAccount")
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_ledger_accounts_ledger_account_id");

                    b.Navigation("BankAccount");

                    b.Navigation("LedgerAccount");
                });

            modelBuilder.Entity("Convivium.Domain.Metering.MeterReading", b =>
                {
                    b.HasOne("Convivium.Domain.Condominiums.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meter_readings_units_unit_id");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Convivium.Domain.People.Membership", b =>
                {
                    b.HasOne("Convivium.Domain.Condominiums.Condominium", "Condominium")
                        .WithMany()
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_condominiums_condominium_id");

                    b.HasOne("Convivium.Domain.People.Person", "Person")
                        .WithMany("Memberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_people_person_id");

                    b.Navigation("Condominium");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Convivium.Domain.People.RefreshToken", b =>
                {
                    b.HasOne("Convivium.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Convivium.Domain.People.UnitOccupancy", b =>
                {
                    b.HasOne("Convivium.Domain.People.Person", "Person")
                        .WithMany("Occupancies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_occupancies_people_person_id");

                    b.HasOne("Convivium.Domain.Condominiums.Unit", "Unit")
                        .WithMany("Occupancies")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_occupancies_units_unit_id");

                    b.Navigation("Person");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Convivium.Domain.Billing.BillingCycle", b =>
                {
                    b.Navigation("Charges");
                });

            modelBuilder.Entity("Convivium.Domain.Billing.Charge", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Convivium.Domain.Condominiums.Block", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Convivium.Domain.Condominiums.Condominium", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Convivium.Domain.Condominiums.Unit", b =>
                {
                    b.Navigation("Occupancies");
                });

            modelBuilder.Entity("Convivium.Domain.Expenses.Supplier", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Convivium.Domain.Finance.BankAccount", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Convivium.Domain.Finance.LedgerAccount", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Convivium.Domain.People.Person", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Occupancies");
                });
#pragma warning restore 612, 618
        }
    }
}
